version: '2'

services:

  mopidy:
    restart: unless-stopped
    build:
      context: mopidy/
      dockerfile: Dockerfile.${HOSTNAME}
      args:
        - SOUNDCLOUD_KEY=$SOUNDCLOUD_KEY
        - HOSTNAME=$HOSTNAME
    volumes:
      - ${MUSIC_DIR}:/var/lib/mopidy/media:ro
      - /mnt/DATA/mopidy-data:/var/lib/mopidy/local
    ports:
      - "6600:6600"
      - "6680:6680"
    devices: 
      - /dev/snd
    user: root
    command: mopidy
