version: '2'

services:

  mopidy:
    build:
      context: mopidy/
      args:
        - SOUNDCLOUD_KEY=$SOUNDCLOUD_KEY
    volumes:
      - /mnt/DATA/music:/var/lib/mopidy/media:ro
      - $PWD/local:/var/lib/mopidy/local
    ports:
      - "6600:6600"
      - "6680:6680"
    devices: 
      - /dev/snd
    user: root
    command: mopidy
